developer-diganta/Dino

css/styles.css
#7 is resolved. Do let me know if there're any more modification required.
=> Added custom scrollbar

background.js, css/styles.css, popup.html, webpage-assets/js/content.js
=> English Dictionary added 

popup.html
=> Fixed the typography error by correcting the paragraph spelling

popup.html
- **Initial Display:-** 
- **Corrected Display:-**
=> Fixed the typography error by correcting the listen spelling in popup.html 

background.js, popup.html, webpage-assets/js/content.js
=> add stop button

.vscode/settings.json, background.js, css/styles.css, popup.html
I have Added Dark mode in a extension. Kindly look into that and feel free to give any suggestions. Thank You!
=>  Add Dark Mode in a extensions

background.js, css/styles.css, popup.html
close #61 
1. Added reader button 
2. Removed user selection option
About 2nd change try to select text its disabled inside extension.
=> Added reader button and removed select option by user

background.js
This PR addresses the issue #63 
This adds a user friendly message "Loading data from API... //" for the duration of the data being fetched from the API.
It happens so fast that i can't take a screenshot for preview but does work.
=> Added Loading animation to API call in dictionary

contributing.md, readme.md
Fixes #73 
Added the steps to contribute to the project using GitHub Desktop and updated the readme file and linked the contributing.md file to it.
- Name: Anish Dubey
- Discord Username: anish27#4262
=> Documentation Improvement

background.js, popup.html, webpage-assets/js/content.js
Fixes #77 
Add an option that would allow italics and underlines to be converted to bold.
Added 3 buttons one which changes the italics to bolds and one which changes underlines to bolds. The third button reverts the action.
initial: right: link, centre: italic, right: underscored text
remove italics
remove underscore
reset
- Name: Justin Dsouza
- Discord Username: ELEMENTO07#2566
=> Feature: Remove italics and underline

background.js, popup.html, webpage-assets/js/content.js
Fixes #(issue)
Added the feature that allows the user to listen to selected text from the webpage.
This issue is addressed in the issue #78
- Name: Harsh Bhagat
- Discord Username: Bhagu#5304
=> Added Selected Text speech

background.js, popup.html, webpage-assets/js/content.js
Fixes #81 
Added border to link Option, previous implementation was to highlight links. Now user has Option to toggle between both methods
Previous implementation of highlighting links
new option to highlight links
reset
- Name: Justin Dsouza
- Discord Username: ELEMENTO07#2566
=> option to select type of highlight for links

background.js, popup.html, webpage-assets/js/content.js
Fixes #69
I have successfully added a lowercase and uppercase button to the dino extension
- Name: MRIDUL MITTAL
- Discord Username: MRIDUL MITTAL #8680
=> Added case Converter (Issue No :#69)

background.js, css/styles.css, popup.html
Fixes #([103](https://github.com/developer-diganta/Dino/issues/103))
Now we can select our desired font for the extension. It will be applied to complete text that is seen in our extension !
Firstly I added select tag in popup file. After that to give functionality to the element I made changes in background.js file.
I added event listener to change the font of DINO whenever the font is changed. I used for loop to loop over all the elements of DINO and then I changed the font-family property of every element and it worked !
Garamond Font 
- Name: (Dheeraj Chhatani)
- Discord Username: (Dheeraj#1420)
=> Add font change feature for DINO

background.js
Fixes #106 
Some words were missing from the word Array That is why the bug happened.
- Name: saalim123
- Discord Username: shxdow192 #2578
=> Fixed text2speech Bug.  Issue #106

css/styles.css
Fixes #100 
I have centered the buttons under magnify section.
- [ x] Bug fix (non-breaking change which fixes an issue)
- [x ] I have read the **CONTRIBUTING** document.
- Name: Papri Majumder
- Discord Username: Papri Majumder#2385
- [x ] I have included the issue number in my PR
=> Centered the buttons under magnify section

css/styles.css, popup.html
Fixes #(111)
As Required Placed case converter Buttons in Single line #111
Enclosed the Buttons tag into a div with class name of "convertBtns"
Made CSS Changes for convertBtns class as display "flex" .
- Name: Sujay V
- Discord Username: Sujay#2174
=> As Required Placed case converter Buttons in Single line #111

popup.html
Fixes #76 
Changed the position of + and - buttons.
- Name: (Your name)
- Discord Username: (Your discord username)
=> Changed the position of '+' and '-' buttons.

readme.md
Fixes #(issue)
Updated Readme.md file.
Added new features and images.
- [`x`] I have updated the documentation accordingly.
- Name: Preksha Thakkar
- Discord Username: preksha#8758
- [`x`] I have included the issue number in my PR
=> Updated Readme.md file #116

css/styles.css
Fixes #(issue)
#75 
Changed the color of sliders.
- Name: (Your name)
- Discord Username: (Your discord username)
=> Changed the color of sliders.

css/styles.css
issue number : #120 
Dino's text here in about section is  set to justify to make it look better. Made some changes in CSS file to justify the content 
- Name: Raja Sudha Sri Harika
- Discord Username: Sri Harika #6571
=> Justify Dino's description in extension

popup.html, webpage-assets/js/content.js
Fixes #(issue)
issue #95 . I have Tahoma font in web page font style and made some changes in content js and popup file.
We have added new feature of the Tahoma font style which is the best font style for those who are suffering from dyslexia.
- Name: Mohammad Nazim Qureshi
- Discord Username: atoz #5954
=> Added Tahoma Font issue#95

css/styles.css, popup.html
Fixes #102 
Description
I have centered the buttons under image section.
Screenshots (if appropriate):
Types of changes
Checklist:
- Name: Sanya Saeed
- Discord:sanya29#3771
=> Center buttons in image section

background.js, css/styles.css, popup.html
Fixes #126 
Updated wordArray
Added a text to indicate the purpose of the checkbox in the header of the popup, updated wordArray in background.js to include the new and missing headers. Additionally centered some poorly formatted headings in the popup for uniformity.
- Name: Madhav Ram
- Discord Username: Madhav#7781
=> wordArray Updated

popup.html
Fixes #104 
Add appropriate ids to sections of extension
currently we have used section tag in our extensions. However do not have any ids to differentiate them. For this simply added an id attribute to the section based on the header.
- Name: Justin Dsouza
- Discord Username: ELEMENTO07#2566
=> add section id's

popup.html
Fixes #153 
- Name: (Durgesh Kumar Prajapati)
- Discord Username: (durgesh4993)
=> Auto scrolling showing two times

background.js, manifest.json, popup.html, webpage-assets/js/content.js
Fixes #(issue)
issue #155. 
I have implemented light-on-dark mode for current active tabs. This is my first experience with the Open Source Project. It's been almost 1 month done after assigning this issue #155. I spent most of my time day on this to solve this issue and being naive it was a big task for me to work on this. In solving this issue, the maintainer helped me with every problem I faced. Overall experience was immensely great. I learned so much through this project. I look forward to working with you again. Thank you again for all your support and help.
I have implemented a Light-on-Dark mode that helps users to enable light and dark modes on this extension.
- Name: Mohammad Nazim Qureshi
- Discord Username: atoz #5954
=> Implemented Light-On-Dark mode for active tabs.
